Turbomole moments
cclib/cclib pull request #1024
Opened 2021-04-01 11:27 UTC by oliver-s-lee

Adds parsing of moments for Turbomole

2021-05-18 04:37 UTC, shivupa commented
(rebased)

2021-05-18 04:37 UTC, shivupa approved these changes

2021-05-19 03:51 UTC, berquist requested changes

2021-05-19 03:51 UTC, berquist commented on cclib/parser/turbomoleparser.py
> +                utils.convertor(float(parts[-1]), "ebohr", "Debye")
The reference point is actually a Cartesian point in space, which probably needs to be converted from bohr to Angstroms.

2021-05-19 03:51 UTC, berquist commented on cclib/parser/turbomoleparser.py
> +                # Assume 0,0,0 as origin if not given.
:+1:

2021-05-24 03:45 UTC, berquist approved these changes

2021-05-24 13:09 UTC, merged