Pull request related to issue #1092
cclib/cclib pull request #1105
Opened 2022-02-08 11:24 UTC by jvalegre

Pull request related to issue #1092. The code broke due to a problem related to the mini print level of ORCA. 

Changes:
1. When parsing ORCA files using the mini print level, cclib raises a warning instead of breaking. The code prints a warning about this, but ideally the users should avoid the mini print level. For example, multiplicity just gets assigned to 1 since it's not included at this print level. The code doesn't break when using the mini level but the fix isn't ideal, since I set rmsDP_value and rmsDP_target to 0.0. 
2.  Final single point E included. This is the final energy, but it wasn't included (I think).

I'm attaching the output files from ORCA and the json files generated with ccwrite, please let me know if you need more information!

[TESTS.zip](https://github.com/cclib/cclib/files/8023283/TESTS.zip)

2022-03-19 17:11 UTC, jvalegre commented
hi @berquist , hope everything is going well! 

I'd like to include similar data for ORCA and NWChem (I only added the GoodVibes parameters for Gaussian). Did you start working on this pull request or I can make a couple more changes to my local cclib code?

Thanks!

2022-06-04 19:07 UTC, berquist requested changes
The most important comment I can give is the one about breaking up this PR into smaller ones based on bug fixes and feature additions.

For the new attributes, https://github.com/cclib/cclib/issues/1093#issuecomment-1018112286 and the documentation were not clear enough about
- what should be placed as attributes on `ccData`,
- what should be a calculation method (under `cclib/methods`), and
- what should be placed in metadata (`ccData.metadata`, a string to _any type_ dict, https://cclib.readthedocs.io/en/latest/data_notes.html#metadata).

I see you put a bunch of stuff under the JSON path for `metadata`.  This is good, but makes me realize that there is no guiding documentation about what to put there, and also that `metadata` is actually an attribute itself (the one linked above).  Rather than let this review sit even longer, though we'll want to change a bunch of locations of things, can you split this PR apart first?

2022-07-04 08:38 UTC, jvalegre commented on cclib/parser/orcaparser.py
> +                    print("WARNING: print level is set to mini, which might cause the loss of relevant information")
done

2022-07-04 08:38 UTC, jvalegre commented on cclib/parser/gaussianparser.py
> +            self.set_attribute('zpve', zpve)
thanks!

2022-07-04 08:46 UTC, jvalegre commented on cclib/parser/gaussianparser.py
> +                    try:
I refactored it, however, this code comes from a previous version that doesn't separate Mulliken & NBO charges and spins (i.e. NBO charges and spins just override Mulliken values). Should I separate charges and spins into charges Mulliken, charges NBO, spins Mulliken and spins NBO?

2022-07-04 09:36 UTC, jvalegre commented on cclib/parser/orcaparser.py
> +            while len(line) > 20 and not 'Total SCF time' in line:  # restricted calcs are terminated by ------
yeah, let me distribute the fixes/additions into Gaussian and ORCA

2022-07-04 14:48 UTC, berquist commented on cclib/parser/gaussianparser.py
> +                    try:
> Should I separate charges and spins into charges Mulliken, charges NBO, spins Mulliken and spins NBO?

Yes please! This must have been an oversight and I can definitely see people would want clearly identified NBO properties. This means parsed output of any NBO calculation right now is incorrect.

2023-08-31 08:47 UTC, closed without merging