Multi parsing with unusual encodings (fix for #1174)
cclib/cclib pull request #1197
Opened 2023-04-26 15:12 UTC by oliver-s-lee

Just as a note, multi-file parsing and single-file parsing now both use `errors = 'ignore'`, which can potentially hide encoding errors.

2023-04-27 03:18 UTC, berquist requested changes

2023-04-27 03:18 UTC, berquist commented on cclib/parser/logfileparser.py
> +def opencompressedfile(filename, mode = "r", object = None, wrap = False):
Let's start trying to use type annotations, even if we don't check them and they aren't necessarily correct the first time, they can be refined later; I'm not sure about `object` or the return type:
```suggestion
def opencompressedfile(filename: str, mode: str = "r", object: typing.Optional[typing.IO] = None, wrap: bool = False) -> typing.IO:
```

2023-04-27 08:10 UTC, oliver-s-lee commented on cclib/parser/logfileparser.py
> +        return fileinput.FileInput(filename, openhook= lambda filename, mode, encoding = None, errors = None: opencompressedfile(filename, mode))
Yeah no worries can do. It's essentially just juggling the call signature so it fits with what FileInput expects, but I think I can write it better. 

I think logging should be possible yeah, let me take a look.

2023-04-28 02:13 UTC, berquist commented on cclib/parser/logfileparser.py
> +def opencompressedfile(filename, mode = "r", object = None, wrap = False):
Oh, it was not so much about the argument being called `object` despite overwriting a built-in...it's just that I don't know what the type is here.

I personally annotate all functions, no matter their visibility.

2023-04-28 02:15 UTC, berquist approved these changes
Thanks for writing tests!

2023-04-28 02:16 UTC, merged

2023-04-28 02:24 UTC, berquist commented
I'm going to make another issue to update the logging, because this is scary looking:
![Screenshot from 2023-04-27 22-22-07](https://user-images.githubusercontent.com/727571/235039078-515ecc0f-cff7-4986-a666-3e5a99f92671.png)