Meta performance
cclib/cclib pull request #1271
Opened 2023-08-31 12:21 UTC by oliver-s-lee

Adds support for number of CPUs and memory used in the calculation in two new metadata keys:
 - `metadata['num_cpus']` - Number of parallel CPUs, integer
 - `metadata['memory']` - Max allowed memory usage in bytes (total, across all CPUs)

WIP for now because we're missing tests

2023-09-04 18:45 UTC, shivupa commented
An acceptable test could just be making sure that the attributes are present for say `dvb_sp` tests. I think this is a nice bite size PR and we could have further improvements be other PRs? or did you want this for other parsers as well?

2023-09-05 07:29 UTC, oliver-s-lee commented
No no I was thinking of leaving it just for these 3 for now, they are my favourites  anyway :)

I think it shouldn't be too hard to check for actual numbers of CPUs/memory, I'll have a look later this week

2023-09-07 11:19 UTC, oliver-s-lee commented
Split memory into `metadata['memory_available']`, which corresponds to the amount of memory requested in the input file, and `metadata['memory_used']` which is the max amount of memory used, as reported by the program (if available).

2023-09-12 23:26 UTC, shivupa requested changes
1 change then Good to merge

2023-09-12 23:26 UTC, shivupa commented on data/Gaussian/basicGaussian16/dvb_gopt.cjson
this file doesn't need to be in this right?

2023-09-13 07:05 UTC, oliver-s-lee commented on data/Gaussian/basicGaussian16/dvb_gopt.cjson
oops, that's what you get for bulk adding folders, deleted

2023-09-20 00:45 UTC, shivupa approved these changes

2023-09-20 00:45 UTC, merged