start psi4 moments attribute parser, turn on tests
cclib/cclib pull request #1471
Opened 2024-08-21 03:42 UTC by amandadumi

Initial conversion for the moments attribute, being done first for Psi4.

There is a reliance on an origin attribute, which i'm unclear on if this is something that can be stored in ccdata, or was only ever meant to exist within the parser.

To Do:
- [x] get attribute in workflow with tests turned on
- [ ] figure out this origin isssue.
- [ ] move the additional moments over
    - [ ] dipole (started)
    - [ ] multipole

2025-02-15 21:14 UTC, berquist commented
In the process of rebasing this now

2025-02-16 02:23 UTC, berquist requested changes

2025-04-30 02:21 UTC, amandadumi commented
Okay I've made some small changes. I naively remove the parser_state object at the end of the parsing with `del`. 

Otherwise this should be good for review when you have the time!

2025-04-30 02:26 UTC, amandadumi commented on cclib/combinator/combinator.py
> +    cprops.parser_metadata,
this was a mistake, but has been fixed!

2025-04-30 02:28 UTC, amandadumi commented on cclib/attribute_parsers/parser_metadata.py
> +class parser_metadata(base_parser):
We discussed this in the meeting, but just so it is documented here: parser_state will hold the small amount of temporary data the original code-based parsers that will be deleted not exposed to the user.

2025-05-04 17:14 UTC, berquist approved these changes
This is good for now.  It will probably get revisited when I try to get rid of all the parse method boilerplate, but that's a separate issue from the problem of where to keep state in a functional program.

2025-05-04 17:15 UTC, merged