PySCF to cclib bridge support
cclib/cclib pull request #1481
Opened 2024-09-17 15:49 UTC by oliver-s-lee

Ok, this is now working to the point where it's ready for at least an initial review.

The main workhorse is `cclib.bridge.cclib2pyscf.cclibfrommethods()` which accepts a number of PySCF method objects (SCF, MP, excited states etc.) and returns a ccData object.

`cclib.bridge.cclib2pyscf.makecclib()` is a slightly nicer wrapper on top that does a good job of guessing what type of PySCF method you pass to it.

Supported so far are:
 - aonames
 - aooverlaps
 - atombasis
 - atomcharges (mulliken and lowdin)
 - atomcoords
 - atommasses
 - atomnos
 - ccenergies (including CCSD(T) although this is slightly fudged due to the way it's handled in PySCF)
 - charge
 - coreelectrons (need to check this is being tested)
 - etenergies
 - etoscs
 - etdips
 - etsecs
 - etsyms (but only multiplicities for now)
 - gbasis
 - geovalues (but only energies, no targets yet)
 - homos
 - metadata (most of important things are here, no performance or timing data yet tho)
 - mocoeffs
 - moenergies
 - moments (both dipole and quadrupole, although quad are only available in development versions of PySCF)
 - mosyms
 - mpenergies (MP2)
 - mult
 - natom
 - nbasis
 - nmo
 - optdone (although slightly hacked due to the way PySCF handles optimisations)
 - optstatus (see above)
 - rotconsts
 - scfenergies (HF and DFT)
 - scftargets
 - scfvalues
 - vibfreqs
 - vibfconsts (although uncertain on units)
 - vibirs
 - vibrmasses

Not currently supported but should be available with only a bit more work
- etdips and friends (just forgot about them)
- grads (not looked for yet)
- hessian (this is readily available, but I'm not knowledgeable enough to understand either the PySCF or cclib formats)
- vibdisps (the IR part of PySCF is not so well documented and I'm not sure where this is hidden)

There are also tests for all of the supported properties (unless I've forgotten of course). The tests use the normal parser tests rather than the ones in `bridge`. To get this to work, I've slightly modified `conftest.py` so `testdata` can specify python files which get imported, run, and the results cached as necessary. Most of the PySCF calcs are extremely quick, but the frequencies on DVB can take a few minutes. Not sure if we want to look at saving the raw PySCF data rather than regenerating each time...

2024-09-17 15:55 UTC, berquist commented
You can get rid of the F821 warnings by prefixing the variable with `_`.

2024-10-07 15:23 UTC, oliver-s-lee commented
At the moment this PR parses energies into hartree, but that change is (or at least should be) in a single commit so easy to reverse if need be.

2024-10-20 21:00 UTC, berquist commented
> At the moment this PR parses energies into hartree, but that change is (or at least should be) in a single commit so easy to reverse if need be.

Ok; sorry to leave you hanging for a review on this.

2024-12-18 04:16 UTC, berquist requested changes
Here is a partial review.

So far I agree with all of your assumptions that I didn't comment on.

2024-12-18 04:16 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +        )  # or do we want velocity?
Yes, length gauge, except for `transprop` where we can store both.

2024-12-18 04:16 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +            if isinstance(etmethod, pyscf.tdscf.rks.TDA):
I'd replace all this with a dict that maps `pyscf` class to the string, and on the dict use `.get(etmethod, type(etmethod).__name__)` to simultaneously handle the default case.

2024-12-18 04:16 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +            attributes["etsyms"].extend([et_mult for i in range(len(etmethod.e))])
```suggestion
            attributes["etsyms"].extend([et_mult for _ in range(len(etmethod.e))])
```

2024-12-18 04:16 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +                x *= 1.0 / np.linalg.norm(x)
IIRC I ripped this from pyscf many years ago, but it indicates that for CIS/TDA you're correct, but if there are deexcitation vectors you need to normalize them together:
```python
    def norm_xy(z: np.ndarray, nocc: int, nvirt: int) -> Tuple[np.ndarray, np.ndarray]:
        x, y = z.reshape(2, nvirt, nocc)
        norm = 2 * (np.linalg.norm(x) ** 2 - np.linalg.norm(y) ** 2)
        norm = 1 / np.sqrt(norm)
        return (x * norm).flatten(), (y * norm).flatten()
```

2024-12-18 04:16 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +        # Dimensions appear to be natoms x natoms x 3 x 3
If true it would then require a reorder to `(3 x natoms, 3 x natoms)`.

2024-12-18 04:16 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +        # TODO: This can include imaginary numbers, convert to 'negative' frequencies?
Yes

2025-01-07 16:03 UTC, oliver-s-lee commented on cclib/bridge/cclib2pyscf.py
> +            if isinstance(etmethod, pyscf.tdscf.rks.TDA):
Sadly we can't do that because then we wouldn't be checking class inheritance (I think the UHF methods base class of these or something). We could iterate over each dictionary key and check but IMO that's no more elegant than the current implementation?

2025-01-07 17:43 UTC, oliver-s-lee commented on cclib/bridge/cclib2pyscf.py
> +                x *= 1.0 / np.linalg.norm(x)
Ah thanks, TD was originally missed because the DVB calculation wouldn't converge for whatever reason, I've now added a new test for TD with water to test the normalisation with both x and y. The implementation is now:

```python
def norm_xy(x, y):
    norm_factor = 1.0 / np.sqrt(
        np.linalg.norm(x) ** 2 - np.linalg.norm(y) ** 2
    )
    return (x * norm_factor, y * norm_factor)
```

This logic is beyond me really, but the `2 *` multiplication factor in your function was giving the wrong results?

2025-01-08 11:06 UTC, oliver-s-lee commented on cclib/bridge/cclib2pyscf.py
> +        # Dimensions appear to be natoms x natoms x 3 x 3
Might have to leave this for now, the reshape is easy enough but we don't currently have a test for hessian values so I can't verify if they're correct. There are probably also some unit conversion issues (I'm unsure what the units for cclib or PySCF are...)

2025-01-15 03:54 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +            if isinstance(etmethod, pyscf.tdscf.rks.TDA):
Ah, I missed that.  This is the way to do it then.

2025-02-16 20:33 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +        # Dimensions appear to be natoms x natoms x 3 x 3
Yes, I'm perfectly fine with leaving TODOs.

2025-02-16 23:09 UTC, berquist requested changes

2025-02-16 23:29 UTC, berquist commented on cclib/bridge/cclib2pyscf.py
> +                x *= 1.0 / np.linalg.norm(x)
This is fine for now but I'm going to try and understand this.

2025-02-24 16:46 UTC, oliver-s-lee commented on test/testdata
> +Basis     PySCF       GenericBasisTest      basicPySCF2.6         dvb_sp.py
Yep no problem.

Personally I'm a YAML fanboy so my default position is yes,  but in this case the table format is actually pretty useful and it would be a shame to lose that. Maybe an argument for the condensed list form?
Eg
```
- [Basis, Psi4,  GenericBasisTest, basicPsi4-1.7, dvb_sp_rks.out]
- [Basis, QChem, GenericBasisTest, basicQChem5.1, dvb_sp.out]
...
```

Or maybe could nest? Something like:
```
Basis:
  Psi4:
    - [GenericBasisTest, basicPsi4-1.7, dvb_sp_rks.out]
  QChem:
    - [GenericBasisTest, basicQChem5.1, dvb_sp.out]
```

2025-02-24 17:03 UTC, oliver-s-lee commented on test/data/testTDun.py
> +# is this class misnamed?
Yeah I'll be honest this did confuse me for a sec, funny how things can slip through. I wonder if the intention was originally to do a delta-SCF type calculation (the original file name in G03 was apparently deltasym.log) and maybe this was the ground state? Just speculation.

That Turbomole one was probably me I'd guess so woops there too. Will address in another PR.

2025-02-25 08:20 UTC, oliver-s-lee commented on test/conftest.py
> +        if "PySCF" in str(first):
Yeah a bit of a mess right now. This 'bridge' does feel quite a lot like a parser, but then again we might want an actual PySCF parser (from the PySCF log files) in the future in which case this guy would need another name or something

2025-03-09 19:38 UTC, berquist commented
This is good for now but am currently rebasing to purge all the pre-commit autofix commits.

2025-04-12 20:01 UTC, berquist commented on pyproject.toml
> +    "geometric"
This is driving me crazy. I would like to push https://github.com/njzjz/openbabel-wheel/issues/6 and https://github.com/openbabel/openbabel/issues/2408 as a solution but not sure I have the energy.

2025-04-12 20:02 UTC, berquist approved these changes
This looks great.  Thanks for all your hard work on it.

2025-04-12 20:18 UTC, merged